Repository Pisyukaev/selectable-grid, pull requests merged in 2023-01, with the labels that each got.

#25 Fix types
  packages/selectable-grid/src/types.ts
Labels: v2.x

#26 chore: bump (lock) dependencies, cleanup project
  .vscode/extensions.json
  examples/react/package.json
  examples/react/public/spanch-bob.webp
  examples/react/src/App.tsx
  examples/react/src/vite-env.d.ts
  examples/react/tsconfig.json
  examples/vanilla/.gitignore
  examples/vanilla/package.json
  examples/vue/.eslintrc.cjs
  examples/vue/.gitignore
  examples/vue/.prettierrc.json
  examples/vue/.vscode/extensions.json
  examples/vue/package.json
  examples/vue/public/favicon.ico
  examples/vue/src/vite-env.d.ts
  examples/vue/tsconfig.config.json
  examples/vue/vite.config.ts
  package.json
  packages/react/package.json
  packages/selectable-grid/package.json
  packages/vue/env.d.ts
  packages/vue/package.json
  packages/vue/src/vite-env.d.ts
  pnpm-lock.yaml
  website/package.json
Labels: v2.x

#30 chore: edited usage api for vue component
  examples/vue/src/App.vue
  packages/vue/src/SelectableGrid.vue
  packages/vue/src/index.ts
Labels: enhancement, v2.x

#31 chore: rename prop
  examples/vanilla/src/index.ts
  packages/react/src/index.tsx
  packages/selectable-grid/src/selectable-grid.ts
  packages/selectable-grid/src/types.ts
  packages/vue/src/SelectableGrid.vue
Labels: enhancement, v2.x

#33 chore: change workflow
  .github/workflows/gh-pages.yaml
  .github/workflows/npm-publish.yaml
Labels: enhancement, v2.x

#35 chore: fixed links on readme files on another packages
  README.md
  packages/react/README.md
  packages/selectable-grid/README.md
  packages/vue/README.md
Labels: enhancement
